<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AUN_QA.SystemService</RootNamespace>
    <UserSecretsId>653689e4-0bcc-4a26-bed1-37fde1379670</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.76.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.76.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
    <PackageReference Include="Stax.AutoDependencyInjectionRegistration" Version="4.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\system.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\audit.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDCA.ServiceDefaults\PDCA.ServiceDefaults.csproj" />
    <ProjectReference Include="..\PDCA.Shared\PDCA.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configs\" />
    <Folder Include="DTOs\CoreFeature\Permission\Requests\" />
    <Folder Include="Entities\" />
    <Folder Include="Infrastructure\" />
  </ItemGroup>

	<ItemGroup>
		<Protobuf Include="..\PDCA.FileService\Protos\file.proto" GrpcServices="Client" Link="Protos\file.proto" />
	</ItemGroup>
</Project>
