syntax = "proto3";

option csharp_namespace = "AUN_QA.SystemService.Protos";

package system;

service SystemProto {
  rpc CheckPermission (CheckPermissionRequest) returns (CheckActionResponse);
  rpc GetUsersByIds (GetUsersByIdsRequest) returns (GetUsersByIdsResponse);
  rpc GetUsersByUsernames (GetUsersByUsernamesRequest) returns (GetUsersByUsernamesResponse);
  rpc SetUsersActived (SetUsersActivedRequest) returns (SetUsersActivedResponse);
  rpc GetUsersByIdsPaged (GetUsersByIdsPagedRequest) returns (GetUsersByIdsPagedResponse);
  rpc UpdateUserProfile (UpdateUserProfileRequest) returns (UpdateUserProfileResponse);
  rpc GetActiveUsersExceptRole (GetActiveUsersExceptRoleRequest) returns (GetActiveUsersExceptRoleResponse);
}

message CheckPermissionRequest {
  string user_id = 1;
  string controller = 2;
  int32 action = 3;
}

message CheckActionResponse {
  bool success = 1;
}

message GetUsersByIdsRequest {
  repeated string user_ids = 1;
}

message UserInfo {
  string id = 1;
  string fullname = 2;
  string avatar = 3;
  string username = 4;
  bool is_actived = 5;
  string email = 6;
}

message GetUsersByIdsResponse {
  repeated UserInfo users = 1;
}

message GetUsersByUsernamesRequest {
  repeated string usernames = 1;
}

message GetUsersByUsernamesResponse {
  repeated UserInfo users = 1;
}

message SetUsersActivedRequest {
  repeated string user_ids = 1;
  bool is_actived = 2;
}

message SetUsersActivedResponse {
  bool success = 1;
}

message GetUsersByIdsPagedRequest {
  repeated string user_ids = 1;
  string text_search = 2;
  int32 page_index = 3;
  int32 page_size = 4;
}

message GetUsersByIdsPagedResponse {
  repeated UserInfo users = 1;
  int32 page_index = 2;
  int32 page_size = 3;
  int32 total_row = 4;
}

message UpdateUserProfileRequest {
  string user_id = 1;
  string fullname = 2;
  string username = 3;
  string email = 4;
  string password = 5;
}

message UpdateUserProfileResponse {
  bool success = 1;
  string message = 2;
  UserInfo user = 3;
}

message GetActiveUsersExceptRoleRequest {
  string excluded_role_id = 1;
}

message GetActiveUsersExceptRoleResponse {
  repeated UserInfo users = 1;
}
