// <auto-generated>
// This code was generated by scripts/generate-permissions.mjs
// Source of Truth: IELTSMaster.Shared/Security/permissions-contract.json
// Version: 1.0.0 | Last Updated: 2026-10-05
// </auto-generated>

using System;
using System.Collections.Generic;

namespace AUN_QA.Shared.Security
{
    public static class GeneratedPermissionKey
    {
        /// <summary>Xem danh sach, tao, khoa, mo khoa, reset password user he thong (SYSTEM)</summary>
        public const string SystemUsersManage = "system:users:manage";

        /// <summary>Chi dinh system role (chi danh cho SYSTEM_OWNER) (SYSTEM)</summary>
        public const string SystemRolesAssign = "system:roles:assign";

        /// <summary>Phe duyet, tu choi, suspend, mo lai tenant, quan ly goi dich vu (SYSTEM)</summary>
        public const string SystemTenantsManage = "system:tenants:manage";

        /// <summary>Xem audit log va thong ke he thong (SYSTEM)</summary>
        public const string SystemAuditView = "system:audit:view";

        /// <summary>Quan ly danh muc dan toc va danh muc chung he thong (SYSTEM)</summary>
        public const string CatalogEthnicGroupsManage = "catalog:ethnic-groups:manage";

        /// <summary>Them, sua, xoa thanh vien, gan role tenant va lien ket phu huynh (TENANT)</summary>
        public const string TenantMembersManage = "tenant:members:manage";

        /// <summary>Quan ly lop hoc, khoa hoc, lich hoc, diem danh va tien do (TENANT)</summary>
        public const string TenantClassesManage = "tenant:classes:manage";

        /// <summary>Chinh sua thong tin trung tam, cau hinh ngay nghi, branding (TENANT)</summary>
        public const string TenantSettingsEdit = "tenant:settings:edit";

        /// <summary>Tao, sua, nhan ban, upload media, AI format de thi va giao trinh (TENANT)</summary>
        public const string ExamsCreate = "exams:create";

        /// <summary>Cham bai thi Writing/Speaking, phan cong cham bai (TENANT)</summary>
        public const string ExamsGrade = "exams:grade";

        /// <summary>Lam bai thi, nop bai lam (TENANT_OR_SYSTEM)</summary>
        public const string ExamsTake = "exams:take";

        /// <summary>Quyen vao portal hoc tap ELearning (TENANT_OR_SYSTEM)</summary>
        public const string ElearningPortalAccess = "elearning:portal:access";

        /// <summary>Bo qua toan bo authorization kiem tra de cuu ho hoac debug he thong (SYSTEM)</summary>
        public const string ElearningBypassAuth = "elearning:bypass:auth";

        public static readonly IReadOnlyList<string> All = new[]
        {
            SystemUsersManage,
            SystemRolesAssign,
            SystemTenantsManage,
            SystemAuditView,
            CatalogEthnicGroupsManage,
            TenantMembersManage,
            TenantClassesManage,
            TenantSettingsEdit,
            ExamsCreate,
            ExamsGrade,
            ExamsTake,
            ElearningPortalAccess,
            ElearningBypassAuth,
        };
    }
}
